nelmio_api_doc:
    documentation:
        info:
            title: Waves Resources Onboarding API
            description: Secure user onboarding, authentication, profile and administration API.
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/api(?!/doc)
