<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260813040000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create profile_images table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE profile_images (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, object_key VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, size INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_profile_images_user ON profile_images (user_id)');
        $this->addSql('ALTER TABLE profile_images ADD CONSTRAINT FK_8AD049A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE profile_images DROP CONSTRAINT FK_8AD049A76ED395');
        $this->addSql('DROP TABLE profile_images');
    }
}
