<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260813020000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create email_verification_tokens table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE email_verification_tokens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, token_hash VARCHAR(64) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_email_verification_token_hash ON email_verification_tokens (token_hash)');
        $this->addSql('CREATE INDEX IDX_C81CA2ACA76ED395 ON email_verification_tokens (user_id)');
        $this->addSql('ALTER TABLE email_verification_tokens ADD CONSTRAINT FK_C81CA2ACA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE email_verification_tokens DROP CONSTRAINT FK_C81CA2ACA76ED395');
        $this->addSql('DROP TABLE email_verification_tokens');
    }
}
